# root
root: true
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint']

env:
  mocha: true
  node: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'

rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-var-requires': off
